---

- name: Include variables specific for the OS family.
  ansible.builtin.include_vars: "{{ item }}"
  with_items:
    - "{{ ansible_os_family }}.yml"

- name: Import install tasks.
  ansible.builtin.import_tasks:
    file: install.yml
